
palette = "grey"

format = """
$username\
@$hostname\
$directory\
$fill \
$git_branch\
$line_break\
$character"""


[character] 
success_symbol = '[➜](bold gray)' 
error_symbol = "[➜](red)"
vimcmd_symbol = "[➜](green)"

[username]
show_always = true
style_user = ""
style_root = ""
format = '[$user]($style)'

[hostname]
disabled = false
ssh_only = false
style = '#d4d4d4'
format = "[$hostname ]($style)"

[directory]
# style = "blue"
# before_repo_root_style = ""
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "


[git_branch]
format = "[$branch]($style)"
style = "white"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "white"

[fill]
symbol = '─'
# style = '#d4d4d4'
style = '#777777'

[palettes.grey]
grey = "#777777"
none = "#777777"
white = "#777777"
rosewater = "#777777"
flamingo = "#777777"
pink = "#777777"
mauve = "#777777"
maroon = "#777777"
peach = "#777777"
sky = "#777777"
sapphire = "#777777"
blue = "#777777"
lavender = "#777777"
text = "#777777"
subtext1 = "#777777"
subtext0 = "#777777"
overlay2 = "#777777"
overlay1 = "#777777"
overlay0 = "#777777"
surface2 = "#777777"
surface1 = "#777777"
surface0 = "#777777"
base = "#777777"
mantle = "#777777"
crust = "#777777"
background = "#777777"
current_line = "#777777"
foreground = "#777777"
comment = "#777777"
cyan = "#777777"
green = "#777777"
orange = "#777777"
purple = "#777777"
red = "#777777"
yellow = "#777777"
