# [[keymaps]]
# command = "NextTrack"
# key_sequence = "<"

# [[keymaps]]
# command = "PreviousTrack"
# key_sequence = ">"


# unknown variant `{VolumeChange = {offset = -5}}`, expected one of `None`, `NextTrack`, `PreviousTrack`, `ResumePause`, `PlayRandom`, `Repeat`, `Shuffle`, `VolumeChange`, `Mute`, `SeekStart`, `SeekForward`, `SeekBackward`, `Quit`, `OpenCommandHelp`, `ClosePopup`, `SelectNextOrScrollDown`, `SelectPreviousOrScrollUp`, `PageSelectNextOrScrollDown`, `PageSelectPreviousOrScrollUp`, `SelectFirstOrScrollToTop`, `SelectLastOrScrollToBottom`, `JumpToCurrentTrackInContext`, `ChooseSelected`, `RefreshPlayback`, `RestartIntegratedClient`, `FocusNextWindow`, `FocusPreviousWindow`, `SwitchTheme`, `SwitchDevice`, `Search`, `Queue`, `ShowActionsOnSelectedItem`, `ShowActionsOnCurrentTrack`, `ShowActionsOnCurrentContext`, `AddSelectedItemToQueue`, `JumpToHighlightTrackInContext`, `BrowseUserPlaylists`, `BrowseUserFollowedArtists`, `BrowseUserSavedAlbums`, `CurrentlyPlayingContextPage`, `TopTrackPage`, `RecentlyPlayedTrackPage`, `LikedTrackPage`, `LyricsPage`, `LibraryPage`, `SearchPage`, `BrowsePage`, `PreviousPage`, `OpenSpotifyLinkFromClipboard`, `SortTrackByTitle`, `SortTrackByArtists`, `SortTrackByAlbum`, `SortTrackByDuration`, `SortTrackByAddedDate`, `ReverseTrackOrder`, `SortLibraryAlphabetically`, `SortLibraryByRecent`, `MovePlaylistItemUp`, `MovePlaylistItemDown`, `CreatePlaylist`


# [[keymaps]]
# command = "VolumeChange"
# key_sequence = "-"

# keymaps = [
#       {
#         command = { VolumeChange = { offset = 2 } };
#         key_sequence = "0";
#       },

#       {
#         command = { VolumeChange = { offset = -2 } };
#         key_sequence = "9";
#       }


[[keymaps]]
command = { VolumeChange = { offset = 2 } }
key_sequence = "0"


[[keymaps]]
command = { VolumeChange = { offset = -2 } }
key_sequence = "9"

[[keymaps]]
command = "Search"
key_sequence = "/"

[[keymaps]]
command = "Search"
key_sequence = "f"

[[keymaps]]
command = "ResumePause"
key_sequence = "space"

[[keymaps]]
command = "ResumePause"
key_sequence = "p"

[[keymaps]]
command = "NextTrack"
key_sequence = "g n"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "g p"

[[keymaps]]
command = "ReverseTrackOrder"
key_sequence = "R"

[[keymaps]]
command = "ChooseSelected"
key_sequence = "enter"

[[keymaps]]
command = "ChooseSelected"
key_sequence = "l"

[[keymaps]]
command = "ClosePopup"
key_sequence = "q"

[[keymaps]]
command = "LibraryPage"
key_sequence = "V"

[[keymaps]]
command = "ClosePopup"
key_sequence = "esc"

[[keymaps]]
command = "ChooseSelected"
key_sequence = "l"

[[keymaps]]
command = "Shuffle"
key_sequence = "z"

[[keymaps]]
command = "Repeat"
key_sequence = "r"

[[keymaps]]
command = "PageSelectNextOrScrollDown"
key_sequence = "J"
repeat = 5

[[keymaps]]
command = "PageSelectPreviousOrScrollUp"
key_sequence = "K"
repeat = 5

[[keymaps]]
command = "SelectFirstOrScrollToTop"
key_sequence = "g g"

[[keymaps]]
command = "SelectLastOrScrollToBottom"
key_sequence = "G"

[[keymaps]]
command = "SortTrackByAddedDate"
key_sequence = "t"

[[keymaps]]
command = "SortTrackByTitle"
key_sequence = "T"

[[keymaps]]
command = "JumpToCurrentTrackInContext"
key_sequence = "."

[[keymaps]]
command = "Queue"
key_sequence = "C-q"

[[keymaps]]
command = { SeekForward = { duration = 10 } }
key_sequence = "<"

[[keymaps]]
command = { SeekBackward = { duration = 10 } }
key_sequence = ">"


[[keymaps]]
command = "PreviousPage"
key_sequence = "h"
