after-login-command = []
after-startup-command = []
start-at-login = false


enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

automatically-unhide-macos-hidden-apps = true

[key-mapping]
    preset = 'qwerty'


[gaps]
    inner.horizontal 	= 15
    inner.vertical 		= 15
    outer.left 			= 15
    outer.bottom 		= 15
    outer.top 			= 15
    # outer.top           = [
        # { monitor."built-in" = 23 },
    # 55]
    outer.right 		= 15


[workspace-to-monitor-force-assignment]
    1 = "OMEN 32q"
    2 = "OMEN 32q"
    3 = "OMEN 32q"
    4 = "Built-in Retina Display"
    5 = "Built-in Retina Display"
    6 = "DELL UP2516D"
    7 = "DELL UP2516D"
    8 = "DELL UP2516D"
    9 = "DELL S2722QC"
    10 = "DELL S2722QC"
    11 = "DELL S2722QC"


[mode.main.binding]

    ctrl-alt-slash = 'layout tiles horizontal vertical'
    ctrl-alt-comma = 'layout accordion horizontal vertical'

    cmd-shift-h = 'focus left --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    cmd-shift-l = 'focus right --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    cmd-shift-k = 'focus up --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'
    cmd-shift-j = 'focus down --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors'

    cmd-shift-1= 'swap left'
    cmd-shift-2= 'swap right'

    alt-shift-1= 'workspace 1'
    alt-shift-2= 'workspace 2'
    alt-shift-3= 'workspace 3'
    alt-shift-4= 'workspace 4'
    alt-shift-5= 'workspace 5'
    alt-shift-6= 'workspace 6'

    # ctrl-1 = 'workspace 1'
    # ctrl-2 = 'workspace 2'
    # ctrl-3 = 'workspace 3'
    # ctrl-4 = 'workspace 4'
    # ctrl-5 = 'workspace 5'
    # ctrl-6 = 'workspace 6'
    # ctrl-7 = 'workspace 7'
    # ctrl-8 = 'workspace 8'
    # ctrl-9 = 'workspace 9'

    # ctrl-alt-i = 'move-node-to-workspace next'
    # ctrl-alt-o = 'move-workspace-to-monitor right'


    cmd-ctrl-h = 'workspace prev'
    cmd-ctrl-l = 'workspace next'

    cmd-shift-8= 'resize smart -100'
    cmd-shift-9= 'resize smart +100'
    cmd-shift-0= 'balance-sizes'

    shift-alt-enter='fullscreen'

    shift-alt-i= ['move-node-to-monitor --wrap-around prev', 'focus-monitor --wrap-around prev']
    shift-alt-o= ['move-node-to-monitor --wrap-around next', 'focus-monitor --wrap-around next']

    cmd-left = ['move-node-to-workspace --wrap-around prev', 'workspace --wrap-around prev']
    cmd-right = ['move-node-to-workspace --wrap-around next', 'workspace --wrap-around next']


    alt-shift-m= 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    f = ['layout floating tiling', 'mode main'] 
    a = ['layout tiles accordion', 'mode main']
    t = ['layout tiles horizontal vertical', 'mode main']

    # j = ['swap down', 'mode main']
    # k = ['swap up', 'mode main']
    # h = ['swap left', 'mode main']
    # l = ['swap right', 'mode main']

    j = ['swap down']
    k = ['swap up']
    h = ['swap left']
    l = ['swap right']


    shift-left = ['join-with left', 'mode main']
    shift-down = ['join-with down', 'mode main']
    shift-up = ['join-with up', 'mode main']
    shift-right = ['join-with right', 'mode main']

    r = 'mode resize'

[mode.resize.binding]
    h = 'resize smart -200'
    l = 'resize smart +200'
    esc = 'mode main'

