"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

keymap = [
	{ on = "<Esc>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "<C-[>", run = "escape",             desc = "Exit visual mode, clear selection, or cancel search" },
	{ on = "q",     run = "quit",               desc = "Quit the process" },
	{ on = "Q",     run = "quit --no-cwd-file", desc = "Quit without outputting cwd-file" },
	{ on = "<C-c>", run = "close",              desc = "Close the current tab, or quit if it's last" },
	{ on = "<C-z>", run = "suspend",            desc = "Suspend the process" },

    { on = [ "J" ], run = "arrow 5", desc = "Move down 5 lines" },
    { on = [ "K" ], run = "arrow -5", desc = "Move up 5 lines" },


	# Hopping
	{ on = "k", run = "arrow prev", desc = "Previous file" },
	{ on = "j", run = "arrow next", desc = "Next file" },

	{ on = "<Up>",   run = "arrow prev", desc = "Previous file" },
	{ on = "<Down>", run = "arrow next", desc = "Next file" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "Go to top" },
	{ on = "G",          run = "arrow bot", desc = "Go to bottom" },

	# Navigation
	{ on = "h", run = "leave", desc = "Back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },

	{ on = "<Left>",  run = "leave", desc = "Back to the parent directory" },
	{ on = "<Right>", run = "enter", desc = "Enter the child directory" },

	{ on = "H", run = "back",    desc = "Back to previous directory" },
	{ on = "L", run = "forward", desc = "Forward to next directory" },


	# { on = "o",         run = "open",                        desc = "Open selected files" },
	# { on = "O",         run = "open --interactive",          desc = "Open selected files interactively" },
	# { on = "<Enter>",   run = "open",                        desc = "Open selected files" },
	# { on = "<S-Enter>", run = "open --interactive",          desc = "Open selected files interactively" },


    # make yazi like lf
    { on = [ "x" ], run = "remove", desc = "Delete" },
    { on = [ "w" ], run = "shell 'pwd | wl-copy' --confirm", desc = "Copy current directory to clipboard" },
    { on = [ "A" ], run = "create --file", desc = "Create file" },
    { on = [ "a" ], run = "create --dir", desc = "Create directory" },
    { on = [ "r" ], run = "rename", desc = "Rename" },
    { on = ["g", "<Space>"], run = "cd --interactive", desc = "Jump interactively" },

    { on = "f",         run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = "F",         run = "search --via=rg",             desc = "Search files by content via ripgrep" },
    
    { on = "~",    run = "help", desc = "Open help" },
    { on = "?",    run = "help", desc = "Open help" },

    {on = "d",     run = "yank --cut", desc = "Cut file"},
    {on = "y",     run = "yank", desc = "Copy file"},
    {on = "p",     run = "paste", desc = "Paste file"},

    { on = [ "s", "f" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "Sort by modified time (reverse)" },
	{ on = [ "s", "n" ], run = "sort alphabetical --reverse=no",                desc = "Sort alphabetically" },
	{ on = [ "s", "N" ], run = "sort alphabetical --reverse",                   desc = "Sort alphabetically (reverse)" },

	{ on = ".",    run = "hidden toggle",                   desc = "hide/show dot files" },

]

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "/"
run = "plugin searchjump"
desc = "searchjump mode"

[[mgr.prepend_keymap]]
on   = [ "i" ]
run = "plugin easyjump"
desc = "easyjump"

